# -*- coding: utf-8 -*-
"""insurance_fraud_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eGnhftLio1p9dXxEOSuYvUvSxRZOX_sZ

# Insurance Fraud Detection using Machine Learning
**Dataset:** Auto Insurance Claims (Kaggle)

**Goal:** Build a Machine Learning model that can predict whether an insurance claim is fraudulent or not.

**Steps we will follow:**
1. Install & Import Libraries
2. Load the Dataset
3. Exploratory Data Analysis (EDA)
4. Data Preprocessing
5. Model Training (Random Forest)
6. Model Evaluation
7. Feature Importance

## Step 1: Install & Import Libraries

We need several Python libraries:
- `pandas` → for handling data (like Excel but in Python)
- `numpy` → for math operations
- `matplotlib` & `seaborn` → for making graphs/charts
- `sklearn` → the main ML library (scikit-learn)
"""

import pandas as pd          # For loading and working with data tables
import numpy as np           # For numerical operations
import matplotlib.pyplot as plt  # For creating plots/charts
import seaborn as sns        # For prettier statistical charts
import warnings
warnings.filterwarnings('ignore')  # Hide unnecessary warnings

# ML libraries
from sklearn.model_selection import train_test_split   # To split data into train & test
from sklearn.preprocessing import LabelEncoder         # To convert text labels to numbers
from sklearn.ensemble import RandomForestClassifier    # Our main ML model
from sklearn.metrics import (classification_report,    # Detailed accuracy report
                              confusion_matrix,         # Shows correct vs wrong predictions
                              accuracy_score,           # Overall accuracy %
                              roc_auc_score,            # AUC score (how good the model is)
                              roc_curve)                # For drawing the ROC curve

print('All libraries imported successfully!')

"""## Step 2: Load the Dataset

We are using the **Auto Insurance Fraud Detection** dataset from Kaggle.

**How to get the dataset:**
1. Go to: https://www.kaggle.com/datasets/buntyshah/auto-insurance-claims-data
2. Download `insurance_claims.csv`


The dataset has **1000 rows** and **40 columns** about insurance claims.
The target column is `fraud_reported` — it is either `Y` (fraud) or `N` (not fraud).
"""

# Load the dataset into a DataFrame (a table in Python)
df = pd.read_csv('insurance_claims.csv')

# Show the first 5 rows to see what the data looks like
print('Shape of dataset:', df.shape)  # (rows, columns)
print('\nFirst 5 rows:')
df.head()

# Check all column names
print('Columns in dataset:')
print(df.columns.tolist())

# Check data types of each column and how many non-null values exist
df.info()

# Basic statistics (mean, min, max etc.) for numerical columns
df.describe()

"""## Step 3: Exploratory Data Analysis (EDA)

EDA means **exploring the data** before building the model.
We want to understand:
- How many fraud vs non-fraud cases are there?
- Are there any missing values?
- What patterns exist in the data?
"""

# --- Check for missing values ---
print('Missing values per column:')
missing = df.isnull().sum()
print(missing[missing > 0])  # Only show columns that have missing values

# Also check for '?' which this dataset uses instead of NaN for some columns
print('\nColumns with ? values:')
for col in df.columns:
    count = (df[col] == '?').sum()
    if count > 0:
        print(f'  {col}: {count} missing values')

# --- Target Variable Distribution ---
# How many fraud (Y) vs not fraud (N) cases?

fraud_counts = df['fraud_reported'].value_counts()
print('Fraud Distribution:')
print(fraud_counts)
print(f'\nFraud percentage: {fraud_counts["Y"] / len(df) * 100:.1f}%')

# Plot it
plt.figure(figsize=(6, 4))
colors = ['#2ecc71', '#e74c3c']  # Green for No fraud, Red for Fraud
fraud_counts.plot(kind='bar', color=colors, edgecolor='black')
plt.title('Fraud vs Non-Fraud Claims', fontsize=14, fontweight='bold')
plt.xlabel('Fraud Reported (N = No, Y = Yes)')
plt.ylabel('Number of Claims')
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig('fraud_distribution.png', dpi=150)  # Save the chart
plt.show()
print('Chart saved!')

# --- Fraud by Incident Type ---
plt.figure(figsize=(10, 5))
incident_fraud = df.groupby('incident_type')['fraud_reported'].value_counts(normalize=True).unstack()
incident_fraud['Y'].sort_values().plot(kind='barh', color='#e74c3c', edgecolor='black')
plt.title('Fraud Rate by Incident Type', fontsize=14, fontweight='bold')
plt.xlabel('Fraud Rate (proportion)')
plt.tight_layout()
plt.savefig('fraud_by_incident.png', dpi=150)
plt.show()

# --- Claim Amount Distribution by Fraud Status ---
plt.figure(figsize=(10, 5))
fraud_yes = df[df['fraud_reported'] == 'Y']['total_claim_amount']
fraud_no  = df[df['fraud_reported'] == 'N']['total_claim_amount']

plt.hist(fraud_no,  bins=30, alpha=0.6, color='#2ecc71', label='Not Fraud')
plt.hist(fraud_yes, bins=30, alpha=0.6, color='#e74c3c', label='Fraud')
plt.title('Claim Amount Distribution: Fraud vs Non-Fraud', fontsize=14, fontweight='bold')
plt.xlabel('Total Claim Amount ($)')
plt.ylabel('Frequency')
plt.legend()
plt.tight_layout()
plt.savefig('claim_amount_dist.png', dpi=150)
plt.show()

# --- Correlation Heatmap (numerical columns only) ---
plt.figure(figsize=(12, 8))
num_cols = df.select_dtypes(include=[np.number]).columns
corr_matrix = df[num_cols].corr()
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm',
            linewidths=0.5, annot_kws={'size': 8})
plt.title('Correlation Heatmap', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('correlation_heatmap.png', dpi=150)
plt.show()

"""## Step 4: Data Preprocessing

Machine Learning models only understand **numbers**, not text.
So we need to:
1. **Remove useless columns** (like policy number, names — these don't help prediction)
2. **Handle missing values** (replace `?` with the most common value)
3. **Encode text columns** (convert `Y/N`, `Male/Female` etc. to `1/0`)
4. **Split into X and y** (X = input features, y = target/answer)
"""

# Make a copy so we don't destroy the original
df_clean = df.copy()

# --- Step 4a: Drop columns that are useless for prediction ---
# These are either IDs, dates, or completely irrelevant info
cols_to_drop = [
    'policy_number',       # Just an ID number
    'policy_bind_date',    # Date — we won't use this
    'policy_state',        # State code — less useful
    'insured_zip',         # ZIP code — too specific
    'incident_date',       # Date of incident
    'incident_location',   # Address text — too specific
    '_c39'                 # This is an empty/junk column in the dataset
]

# Only drop columns that actually exist in our dataset
cols_to_drop = [c for c in cols_to_drop if c in df_clean.columns]
df_clean = df_clean.drop(columns=cols_to_drop)

print(f'Columns removed: {cols_to_drop}')
print(f'Remaining columns: {df_clean.shape[1]}')

# --- Step 4b: Handle '?' missing values ---
# Replace '?' with NaN first, then fill with most common value (mode)

df_clean = df_clean.replace('?', np.nan)  # Replace ? with NaN

# For each column with missing values, fill with the most common value
for col in df_clean.columns:
    if df_clean[col].isnull().sum() > 0:
        most_common = df_clean[col].mode()[0]  # Most frequent value
        df_clean[col] = df_clean[col].fillna(most_common)
        print(f'  Filled "{col}" with "{most_common}"')

print('\nMissing values handled!')
print('Remaining nulls:', df_clean.isnull().sum().sum())

# --- Step 4c: Encode text (categorical) columns to numbers ---
# ML models need numbers. We use LabelEncoder to convert text to numbers.
# Example: 'Male' → 0, 'Female' → 1

le = LabelEncoder()  # Create a LabelEncoder object

# Find all columns that have text (object) data type
text_cols = df_clean.select_dtypes(include=['object']).columns.tolist()
print(f'Text columns to encode ({len(text_cols)} total):')

for col in text_cols:
    df_clean[col] = le.fit_transform(df_clean[col].astype(str))
    print(f'  Encoded: {col}')

print('\nAll text columns converted to numbers!')

# --- Step 4d: Separate features (X) and target (y) ---
# X = all input columns (what the model learns from)
# y = the answer column (fraud_reported: 0 = No, 1 = Yes)

X = df_clean.drop(columns=['fraud_reported'])  # Everything except the target
y = df_clean['fraud_reported']                 # Just the target column

print(f'Features (X) shape: {X.shape}')  # Should be (1000, ~32)
print(f'Target  (y) shape: {y.shape}')   # Should be (1000,)
print(f'\nFraud cases in y: {y.sum()} out of {len(y)}')

# --- Step 4e: Split into Training and Testing sets ---
# We train the model on 80% of data, and TEST it on the remaining 20%
# This way we can check how the model performs on data it has never seen!

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,       # 20% for testing
    random_state=42,     # Fixed seed for reproducibility
    stratify=y           # Keep same fraud ratio in train & test
)

print(f'Training set size:  {X_train.shape[0]} samples')
print(f'Testing  set size:  {X_test.shape[0]} samples')
print(f'\nFraud in training: {y_train.sum()} cases')
print(f'Fraud in testing:  {y_test.sum()} cases')

"""## Step 5: Model Training

We will use **Random Forest Classifier**.

**What is Random Forest?**
- It builds many Decision Trees (like a forest of trees)
- Each tree learns slightly different patterns from the data
- Final prediction = majority vote from all trees
- It's very accurate and handles messy data well

Think of it like asking 100 doctors for a diagnosis — the majority answer is usually right.
"""

# --- Create and Train the Random Forest model ---

rf_model = RandomForestClassifier(
    n_estimators=100,    # Build 100 decision trees
    max_depth=10,        # Each tree can be at most 10 levels deep
    random_state=42,     # For reproducibility
    class_weight='balanced'  # Handle imbalanced fraud/non-fraud ratio
)

# Train the model — this is where the learning happens!
rf_model.fit(X_train, y_train)

print('Model trained successfully!')
print(f'Number of trees in the forest: {rf_model.n_estimators}')

"""## Step 6: Model Evaluation

Now we test the model on the **20% test data** it has never seen.

Key metrics we will check:
- **Accuracy** → % of correct predictions overall
- **Precision** → Of all predicted frauds, how many were actually fraud?
- **Recall** → Of all actual frauds, how many did we catch?
- **F1 Score** → Balance between Precision and Recall
- **AUC Score** → Overall model quality (closer to 1.0 = better)
"""

# --- Make predictions on the test set ---
y_pred = rf_model.predict(X_test)           # Predicted class (0 or 1)
y_prob = rf_model.predict_proba(X_test)[:, 1]  # Probability of fraud (for ROC curve)

# --- Print key metrics ---
acc = accuracy_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_prob)

print('=' * 50)
print('       MODEL EVALUATION RESULTS')
print('=' * 50)
print(f'Accuracy  : {acc * 100:.2f}%')
print(f'AUC Score : {auc:.4f}')
print('=' * 50)
print('\nDetailed Classification Report:')
print(classification_report(y_test, y_pred, target_names=['Not Fraud', 'Fraud']))

# --- Confusion Matrix ---
# Shows: how many fraud cases did we correctly catch?
# And how many did we wrongly flag as fraud?

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Not Fraud', 'Fraud'],
            yticklabels=['Not Fraud', 'Fraud'])
plt.title('Confusion Matrix', fontsize=14, fontweight='bold')
plt.ylabel('Actual Label')
plt.xlabel('Predicted Label')
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150)
plt.show()

# Explain what the matrix means
tn, fp, fn, tp = cm.ravel()
print(f'True Negatives  (correctly said NOT fraud): {tn}')
print(f'False Positives (wrongly said fraud):        {fp}')
print(f'False Negatives (missed actual fraud):       {fn}')
print(f'True Positives  (correctly caught fraud):    {tp}')

# --- ROC Curve ---
# This curve shows the trade-off between catching fraud vs raising false alarms
# A curve closer to the top-left corner = better model

fpr, tpr, thresholds = roc_curve(y_test, y_prob)

plt.figure(figsize=(7, 5))
plt.plot(fpr, tpr, color='#e74c3c', lw=2, label=f'ROC Curve (AUC = {auc:.3f})')
plt.plot([0, 1], [0, 1], color='gray', linestyle='--', label='Random Guess')
plt.fill_between(fpr, tpr, alpha=0.1, color='#e74c3c')
plt.xlabel('False Positive Rate (False Alarm Rate)')
plt.ylabel('True Positive Rate (Fraud Detection Rate)')
plt.title('ROC Curve - Random Forest', fontsize=14, fontweight='bold')
plt.legend(loc='lower right')
plt.tight_layout()
plt.savefig('roc_curve.png', dpi=150)
plt.show()

"""## Step 7: Feature Importance

Which features (columns) did the model find most useful for detecting fraud?

Random Forest can tell us how important each feature was — this is very useful to understand the model.
"""

# --- Get feature importances from the trained model ---
feature_names = X.columns.tolist()
importances = rf_model.feature_importances_

# Create a DataFrame for easy viewing and sorting
feat_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importances
}).sort_values('Importance', ascending=False)

# Show top 15 most important features
print('Top 15 Most Important Features for Fraud Detection:')
print(feat_df.head(15).to_string(index=False))

# --- Plot Feature Importance ---
top15 = feat_df.head(15)

plt.figure(figsize=(10, 7))
colors = plt.cm.RdYlGn(np.linspace(0.2, 0.8, len(top15)))[::-1]
bars = plt.barh(top15['Feature'][::-1], top15['Importance'][::-1],
                color=colors, edgecolor='black')
plt.title('Top 15 Features for Fraud Detection', fontsize=14, fontweight='bold')
plt.xlabel('Feature Importance Score')
plt.tight_layout()
plt.savefig('feature_importance.png', dpi=150)
plt.show()

"""## Summary

| Step | What We Did |
|------|-------------|
| 1 | Imported libraries |
| 2 | Loaded insurance claims dataset (1000 rows, 40 columns) |
| 3 | Explored data — found ~24% fraud cases |
| 4 | Cleaned data: removed useless columns, handled missing values, encoded text |
| 5 | Trained a Random Forest model (100 trees) |
| 6 | Evaluated — achieved ~85% accuracy, AUC ~0.87 |
| 7 | Identified top fraud-detecting features |

### Key Takeaway
The Random Forest model successfully learns patterns in insurance claims and can flag fraudulent claims with good accuracy. In real-world use, this model would help insurance companies save money by automatically flagging suspicious claims for human review.
"""